# Generated by Django 5.0.6 on 2024-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=10)),
            ],
        ),
    ]
