# Generated by Django 5.0.6 on 2024-06-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
