# Generated by Django 5.0.6 on 2024-06-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
