# Generated by Django 5.0.6 on 2024-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('order_details', models.JSONField()),
                ('order_status', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
