# Generated by Django 5.0.6 on 2024-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_meja', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
